# 실제 배치 위치: .github/workflows/stage-user-api.yml
#
# stage/user-api 브랜치에 push하면 user-api가 테스트 서버에 배포된다.
# 어떤 파일이 변경되었는지와 무관하게 항상 배포된다.

name: Stage user-api

on:
  push:
    branches:
      - stage/user-api
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/backend-cd.yml
    with:
      project: user-api
      gradle-module: ':apps:user-api'
    secrets:
      SERVER_HOST: ${{ secrets.STAGE_USER_API_SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
