# 실제 배치 위치: .github/workflows/deploy-admin-api.yml
#
# deploy/admin-api 브랜치에 push하면 admin-api가 배포된다.
# 어떤 파일이 변경되었는지와 무관하게 항상 배포된다.

name: Deploy admin-api

on:
  push:
    branches:
      - deploy/admin-api
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      project: admin-api
      gradle-module: ':apps:admin-api'
    secrets: inherit
